module.exports = {
    newspaper: 'The Daily News',
    mainArticle: {
        title: 'Main Article',
        body: 'Spicy jalapeno bacon ipsum dolor amet tongue leberkas pork loin beef ribs ham chuck ground round. Strip steak pork chop pork belly biltong pig short loin chuck, burgdoggen tri-tip sausage salami turducken turkey leberkas alcatra. Short ribs ham prosciutto strip steak pork chop capicola meatloaf chuck kevin sirloin biltong jerky venison boudin. Spare ribs porchetta pork chop, tri-tip flank pastrami pork ribeye shoulder fatback turkey frankfurter. Rump pastrami venison jerky pork chop beef, beef ribs turkey. T-bone short ribs spare ribs, pork belly capicola pancetta ribeye pork chop prosciutto filet mignon tri-tip. Picanha ham hock pork belly landjaeger bresaola fatback, shank filet mignon kielbasa strip steak tongue pork loin beef drumstick. Kevin prosciutto brisket jerky cow, pastrami meatball swine. Meatball tri-tip tail pig corned beef biltong rump boudin swine ribeye short loin beef buffalo shankle t-bone. Pork chuck pork chop kielbasa ball tip ground round. Pork belly cupim turkey, biltong ball tip kielbasa salami sausage hamburger sirloin boudin pork loin ham porchetta burgdoggen. Ham hock pork t-bone, kevin leberkas ground round bacon cupim short loin tenderloin tail sausage. Pancetta ball tip bacon ham, pork belly sirloin landjaeger. Beef ribs pancetta kielbasa turducken, t-bone short loin tail tongue ham hock cow boudin tri-tip salami andouille. Alcatra spare ribs meatloaf, porchetta ham pork loin ball tip chicken. Jerky meatloaf hamburger drumstick kevin t-bone, buffalo kielbasa bacon. Sirloin meatball strip steak chicken, pork loin ham tongue swine drumstick fatback. Tenderloin short loin flank bresaola, filet mignon venison boudin. Ground round shank drumstick capicola fatback ham hock sirloin, tri-tip biltong tongue chuck tenderloin shoulder corned beef pork loin. Tongue jowl flank meatball pork chop. Ribeye spare ribs pork loin pancetta drumstick kevin sausage strip steak pig short loin. Ham tail tenderloin, bresaola andouille turducken turkey spare ribs meatloaf ribeye. Prosciutto andouille venison, shankle spare ribs swine ham hock ribeye bacon pork picanha pork loin. Tongue beef shoulder, pork spare ribs boudin landjaeger shankle pork belly filet mignon capicola flank brisket. Cupim meatloaf chicken, brisket andouille shoulder venison tongue sausage ribeye buffalo flank kevin. Rump pork loin alcatra beef ribs burgdoggen boudin andouille filet mignon landjaeger biltong chuck. Brisket porchetta ground round beef tri-tip. Frankfurter picanha tail turkey pancetta cupim pork loin pork belly boudin ham. Meatball porchetta filet mignon pancetta buffalo sirloin, leberkas pork strip steak drumstick beef ribs jerky shankle. Corned beef ham hock leberkas, pastrami turkey buffalo short ribs sausage frankfurter drumstick tenderloin beef ribs meatball filet mignon. Venison salami frankfurter doner.'
    },
    shortArticle: {
        title: 'Side/Bottom Article',
        body: 'Cupcake ipsum dolor sit amet. Topping icing biscuit sesame snaps chupa chups marshmallow. Sweet candy topping wafer toffee muffin cake. Gummies I love ice cream sesame snaps gummies donut oat cake. Caramels I love bonbon donut gingerbread dessert dragée. Sesame snaps cake lemon drops tootsie roll lollipop I love sweet roll topping apple pie. Sweet lemon drops biscuit marzipan carrot cake croissant jelly biscuit icing. Candy canes cupcake soufflé I love carrot cake pudding apple pie. Liquorice pudding soufflé marshmallow cake muffin. Bear claw caramels bonbon lollipop. Muffin chocolate bar I love carrot cake carrot cake jelly. I love gummi bears topping brownie oat cake. Candy canes oat cake powder. Sweet roll carrot cake I love gingerbread chocolate cake I love pastry brownie. Jelly-o wafer tiramisu chupa chups. Candy marshmallow lollipop toffee muffin fruitcake cookie. Carrot cake bonbon muffin pudding dessert I love.'
    }
}